apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: core.gitops-with-tanzu.github.com
spec:
  displayName: GitOps with Tanzu - Core
  longDescription: Core packages for Tanzu clusters
  shortDescription: Core packages for Tanzu clusters
  providerName: GitOps with Tanzu
  maintainers:
  - name: Alexandre Roman
  supportDescription: Go to github.com/alexandreroman/gitops-with-tanzu for documentation
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: core.gitops-with-tanzu.github.com.1.0.0
spec:
  refName: core.gitops-with-tanzu.github.com
  version: 1.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/alexandreroman/gitops-with-tanzu-core:stable
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
