apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: monitoring.gitops-with-tanzu.github.com
spec:
  displayName: GitOps with Tanzu - Monitoring
  longDescription: Monitoring packages for Tanzu clusters
  shortDescription: Monitoring packages for Tanzu clusters
  providerName: GitOps with Tanzu
  maintainers:
  - name: Alexandre Roman
  supportDescription: "Go to github.com/alexandreroman/gitops-with-tanzu for documentation"
