apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: monitoring.gitops-with-tanzu.github.com.1.0.0
spec:
  refName: monitoring.gitops-with-tanzu.github.com
  version: 1.0.0
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: ghcr.io/alexandreroman/gitops-with-tanzu-monitoring:stable
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
