#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")
#@ load("@ytt:base64", "base64")

#@ def config():
namespace: tanzu-system-dashboards
grafana:
  secret:
    admin_user: #@ base64.encode(data.values.grafana.admin.user)
    admin_password: #@ base64.encode(data.values.grafana.admin.password)
  deployment:
    replicas: #@ data.values.grafana.replicas
  pvc:
    storageClassName: #@ data.values.grafana.storage.className
    storage: #@ data.values.grafana.storage.size
  service:
    type: ClusterIP
ingress:
  enabled: true
  virtual_host_fqdn: #@ data.values.grafana.ingress.host
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name": "grafana-pkg-values"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
