#@ load("@ytt:data", "data")

#@ if len(data.values.metallb.addresses) > 0:
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: metallb
  annotations:
    packaging.carvel.dev/downgradable: ""
    kapp.k14s.io/change-group: "gitops-with-tanzu/metallb"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/tanzu-extra-repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/tanzu-extra-repo"
spec:
  packageRef:
    refName: metallb.extra.tanzu.vmware.com
    versionSelection:
      constraints: 0.10.3
      prereleases: {}
  serviceAccountName: core-default-sa
  values:
  - secretRef:
      name: metallb-pkg-values
#@ end
