apiVersion: v1
kind: Secret
metadata:
  name: metallb-pkg-values
  annotations:
    kapp.k14s.io/change-group: "gitops-with-tanzu/metallb"
    kapp.k14s.io/change-rule.create-order: "upsert after upserting gitops-with-tanzu/tanzu-extra-repo"
    kapp.k14s.io/change-rule.delete-order: "delete before deleting gitops-with-tanzu/tanzu-extra-repo"
type: Opaque
stringData:
  values.yml:
